import style from './global.scss'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" style={{ style }}>
			<body>{children}</body>
		</html>
	)
}
